// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWCF5ibEONEg0XL-dRjoDUUXMg4qRxnSg',
    appId: '1:14710582040:android:80aac04e2a2608587d0c6d',
    messagingSenderId: '14710582040',
    projectId: 'nocard-8151',
    storageBucket: 'nocard-8151.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfuoUr-ziuFehWG4LUZO6ytvgag0uaMmA',
    appId: '1:14710582040:ios:4c175277d3a26fe27d0c6d',
    messagingSenderId: '14710582040',
    projectId: 'nocard-8151',
    storageBucket: 'nocard-8151.appspot.com',
    androidClientId: '14710582040-eo71gl7tl5drukaqjk10nbv6ugq96pku.apps.googleusercontent.com',
    iosClientId: '14710582040-l6sle6qkimul7nqpgq42i6jihae8luj0.apps.googleusercontent.com',
    iosBundleId: 'com.example.nearbyNocard',
  );
}
